### ISSUE TITLE
Please create new route for adding multiple roles

### ISSUE THREAD

**Issue by Who1sthatdude** [AtlasRender/atlas-core#224] opened 2020-12-18 16:10 UTC
# Feature request
## Is your feature request related to a problem? Please describe.
No promblems my friend

## Describe the solution you'd like 🌟
I would like you to solve this

## Describe alternatives you've considered 🐾
None

## Additional context 👍:
None

**Comment by JeyM1** [comment] 2021-01-06 16:49
duplicate of #230

**Closed by JeyM1** 2021-01-06 16:49 UTC
Labels: enhancement
