### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by DanilAndreev** [AtlasRender/atlas-core#128] opened 2020-11-04 13:47 UTC
# Describe the bug 👀

For example, in __RolesController_ in ```getRoles()``` method when you try to ```throw new RequestError(404, "Not found.");``` it crashes promise, but not sets response headers to 404 status.

## How to reproduce 🏃:

1. In request to ```http://origin:3002/organizations/1/roles``` do not set body.
2. Set method ___GET___.
3. Send request.
4. Get request timeout and error on the server.

## Expected behavior 🙌
All controllers errors __MUST be handeled__ and turned to ```ctx.status```.

## Screenshots ✨

![image](https://user-images.githubusercontent.com/33941552/98119069-c7cd5000-1eb4-11eb-919c-dd1012cb02cf.png)

### Desktop 💻:
 - OS: Container-Optimized OS (cos)
 - Browser: none
 - Version latest

**Comment by JeyM1** [comment] 2020-11-04 14:20
All controller's errors are handled [__inside__ ___Server's___ temporary error handler](https://github.com/AtlasRender/atlas-core/blob/88c9ef21648b060fc64be4f3826957c62f2402f3/src/core/Server.ts#L193).
[This line](https://github.com/AtlasRender/atlas-core/blob/88c9ef21648b060fc64be4f3826957c62f2402f3/src/core/Server.ts#L198) prints the error in console for debug.
So error handling is not incorrect. It is just not ready.
As about status codes, I get 404 when reproducing:
![image](https://user-images.githubusercontent.com/46285162/98122730-a91d8800-1eb9-11eb-8a37-f92469bd63b9.png)

**Comment by JeyM1** [comment] 2020-11-07 16:08
@DanilAndreev ?

**Comment by DanilAndreev** [comment] 2020-11-08 01:36
> @DanilAndreev ?

What do you want to hear?

**Comment by JeyM1** [comment] 2020-11-08 11:07
> > @DanilAndreev ?
> 
> What do you want to hear?

Answered above, but had no feedback.
I assume we need to close this and add another task to improve current error handler, because I dont understand this problem / it's outdated

**Comment by DanilAndreev** [comment] 2020-11-08 11:12
I thought, you laveled it with __development__ label for finishing this issue. You said, that it isn't finished.

**Comment by DanilAndreev** [comment] 2020-11-08 11:13
> (your comment, I have edited it by mistake)

If it is outdated - mark this issue with outdated label. If it us done - clode the issue.

**Closed** 2021-01-06 19:15 UTC
Labels: development
