### ISSUE TITLE
Add role permissions

### ISSUE THREAD

**Issue by ZaykaNya** [AtlasRender/atlas-core#133] opened 2020-11-05 22:57 UTC
# Feature request
## Is your feature request related to a problem? Please describe.

Add role permissions for Add/Modify User Dialog on Organization Page.

## Describe the solution you'd like 🌟

Modify route for role permissions
route: 
__[GET]__ ___/organizations/:organization_id/users___

![image](https://user-images.githubusercontent.com/48089558/98305700-09e8b580-1fcb-11eb-8f35-141e606eebc2.png)

**Comment by JeyM1** [comment] 2020-11-05 23:00
Duplicate of #95.

**Closed by JeyM1** 2020-11-05 23:00 UTC
Labels: enhancement
